import { createOpencodeClient } from "@opencode-ai/sdk";
import { runPipeline } from "./dist/pipeline.js";

// Connect to already-running OpenCode server
const client = createOpencodeClient({ baseUrl: "http://127.0.0.1:4097" });
console.log("Connected to OpenCode server\n");

const brief = `
Write a 150-word intro paragraph for a CMO white paper on AI changing the role of creative agencies.
Audience: CMOs and marketing leaders at mid-to-large companies.
Tone: analytical, confident, near-neutral.
Evidence available: Gartner estimates 30% of outbound marketing messages will be AI-generated by 2025. Many agencies are rethinking their value proposition.
No fluff. No hype. Get to the point.
`.trim();

console.log("Brief:", brief);
console.log("\n" + "=".repeat(60) + "\n");

try {
  const output = await runPipeline(brief, client);
  console.log("\n" + "=".repeat(60));
  console.log("FINAL OUTPUT:");
  console.log("=".repeat(60));
  console.log(output);
} catch (err) {
  console.error("Pipeline error:", err.message || err);
  if (err.stack) console.error(err.stack);
  process.exit(1);
}
process.exit(0);
