import { createOpencodeClient } from "@opencode-ai/sdk";
import { runPipeline } from "./dist/pipeline.js";

const client = createOpencodeClient({ baseUrl: "http://127.0.0.1:4098" });
console.log("Connected to OpenCode server\n");

const brief = `
Write a 150-word intro paragraph for a CMO white paper.
Title: "What AI Takes From Agencies (And What It Can't)"
Central argument: AI is replacing the repeatable execution work agencies do, but the strategic judgment and cultural fluency that makes great creative work can't be automated — and CMOs who understand this will build better partnerships.
Audience: CMOs and marketing leaders at mid-to-large consumer brands.
Tone: analytical, confident, near-neutral. Advising a respected peer.
Agency type in scope: full-service creative agencies.
The intro should set up the problem (AI disrupting agency work), not recommend an action yet.
Evidence: Gartner estimates 30% of outbound marketing messages will be AI-generated by 2025. McKinsey reports that generative AI could automate 60-70% of employee time in some roles.
No title needed in the output — just the intro paragraph.
`.trim();

console.log("Brief:", brief);
console.log("\n" + "=".repeat(60) + "\n");
console.log("Running 5-step pipeline (this takes a few minutes)...\n");

const start = Date.now();
try {
  const output = await runPipeline(brief, client);
  const elapsed = Math.round((Date.now() - start) / 1000);
  console.log(`\n(Pipeline completed in ${elapsed}s)\n`);
  console.log("=".repeat(60));
  console.log("FINAL OUTPUT:");
  console.log("=".repeat(60));
  console.log(output);
} catch (err) {
  console.error("Pipeline error:", err.message || err);
  if (err.stack) console.error(err.stack);
  process.exit(1);
}
process.exit(0);
