import { createOpencodeClient } from "@opencode-ai/sdk"
import { beforeAll, describe, expect, it } from "vitest"

import { runDraftWithArtifact } from "../../src/pipeline.js"

const OPENCODE_URL = process.env.OPENCODE_URL ?? "http://127.0.0.1:4098"

describe("Draft E2E", { timeout: 600_000 }, () => {
  let client: ReturnType<typeof createOpencodeClient>

  beforeAll(() => {
    client = createOpencodeClient({ baseUrl: OPENCODE_URL })
  })

  it("returns the structured public draft envelope by default", async () => {
    const brief = `
      Draft a 100-word intro for a CMO white paper.
      Title: "What AI Takes From Agencies (And What It Can't)"
      Audience: CMOs at consumer brands.
      Tone: analytical, near-neutral.
      Evidence: Gartner estimates 30% of outbound messages will be AI-generated by 2025.
    `.trim()

    const output = await runDraftWithArtifact(brief, client)

    expect(output.agent).toBe("corina")
    expect(output.capability).toBe("draft")
    expect(["success", "degraded", "failed"]).toContain(output.outcome)
    expect(typeof output.should_persist).toBe("boolean")
    expect(Array.isArray(output.warnings)).toBe(true)
    expect(output.metrics).toBeDefined()
    expect(output.rendered).toBeTruthy()

    if (output.outcome === "failed") {
      expect(output.should_persist).toBe(false)
      expect(output.artifact).toBeNull()
      return
    }

    expect(output.should_persist).toBe(true)
    expect(output.artifact).toBeTruthy()
    expect(output.artifact?.final_content).toBeTruthy()
    expect(output.artifact?.final_content.length).toBeGreaterThan(0)
    expect(output.artifact?.audit).toBeDefined()
  })
})
