import { createOpencodeClient } from "@opencode-ai/sdk"
import { beforeAll, describe, expect, it } from "vitest"

import { runPipeline } from "../../src/pipeline.js"

const OPENCODE_URL = process.env.OPENCODE_URL ?? "http://127.0.0.1:4098"

describe("Pipeline E2E", { timeout: 600_000 }, () => {
  let client: ReturnType<typeof createOpencodeClient>

  beforeAll(() => {
    client = createOpencodeClient({ baseUrl: OPENCODE_URL })
  })

  it("runs the full pipeline and returns a non-empty string", async () => {
    const brief = `
      Write a 100-word intro for a CMO white paper.
      Title: "What AI Takes From Agencies (And What It Can't)"
      Audience: CMOs at consumer brands.
      Tone: analytical, near-neutral.
      Evidence: Gartner estimates 30% of outbound messages will be AI-generated by 2025.
    `.trim()

    const output = await runPipeline(brief, client)
    expect(output).toBeTruthy()
    expect(output.length).toBeGreaterThan(100)
    expect(output).not.toContain("I hope this helps")
    expect(output).not.toContain("Let me know if")
  })
})
